pyconcz/common/urls.py
from django.conf.urls import url

from pyconcz.common.views import tickets_index, tickets_ajax_content


urlpatterns = [
    url('^$', tickets_index, name='tickets'),
    url('^ajax-content$', tickets_ajax_content, name='tickets_ajax_content'),
]

pyconcz/sponsors/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from pyconcz.sponsors.views import sponsors_list


urlpatterns = [
    url('^$', sponsors_list, name='sponsors_list'),

    url(r'^offer/$',
        TemplateView.as_view(template_name='pages/sponsors_offer.html'),
        name='sponsors_offer'),
]

pyconcz/team/urls.py
from django.conf.urls import url

from pyconcz.team.views import team_list


urlpatterns = [
    url('^$', team_list, name='team_list'),
]

pyconcz/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView

from pyconcz.common.views import homepage

prefixed_urlpatterns = [
    url(r'^$', homepage, name='homepage'),
    url(r'^programme/', include('pyconcz.programme.urls')),
    url(r'^team/', include('pyconcz.team.urls')),
    url(r'^proposals/', include('pyconcz.proposals.urls')),
    url(r'^announcements/', include('pyconcz.announcements.urls')),
    url(r'^sponsors/', include('pyconcz.sponsors.urls')),
    url(r'^tickets/', include('pyconcz.common.urls')),
    url(r'^intermission/', include('pyconcz.intermission.urls', namespace='intermission')),

    # static pages
    url(r'^coc/$', TemplateView.as_view(template_name='pages/coc.html'), name='coc'),
    url(r'^privacy-policy/$', TemplateView.as_view(template_name='pages/privacy_policy.html'), name='privacy_policy'),
    url(r'^ostrava/$', TemplateView.as_view(template_name='pages/ostrava.html'), name='city'),
    url(r'^venue/$', TemplateView.as_view(template_name='pages/venue.html'), name='venue'),
    url(r'^board-game-night/$', TemplateView.as_view(template_name='pages/board_game_night.html'), name='board_game_night'),
    url(r'^workshop-leaders-info/$', TemplateView.as_view(template_name='pages/workshop_leaders_info.html'), name='workshop_leaders_info'),
    url(r'^pattern-lib/$', TemplateView.as_view(template_name='pages/pattern_lib.html'), name='pattern_lib'),

    # redirects to external websites
    url(r'^video/$', RedirectView.as_view(url='https://www.youtube.com/watch?v=kL2gmhs0irI')),


    # static pages
    # url(r'^transparency-report/$', TemplateView.as_view(template_name='pages/transparency.html'), name='about_transparency'),

    # old urls redirect (delete when changing 2019 to 2020)
    url(r'^about/code/?$', RedirectView.as_view(url='/2019/coc/', permanent=True)),
    url(r'^about/privacy/?$', RedirectView.as_view(url='/2019/privacy-policy/', permanent=True)),
    url(r'^about/team/?$', RedirectView.as_view(url='/2019/team/', permanent=True)),
]

urlpatterns = (
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        [
            url(r'^coc/$', RedirectView.as_view(url='/2019/coc/')),
            url(r'^2019/', include(prefixed_urlpatterns)),
            url(r'^admin/', include(admin.site.urls)),
            url(r'^$', RedirectView.as_view(url='/2019/')),
        ]
)

pyconcz/sponsors/models.py
from django.db import models

from extended_choices import Choices

from django.utils.text import slugify


class Sponsor(models.Model):
    LEVELS = Choices(
        ('platinum', 1, 'Platinum'),
        ('gold', 2, 'Gold'),
        ('silver', 3, 'Silver'),
        ('bronze', 4, 'Bronze'),
        ('diversity', 5, 'Diversity'),
        ('media', 6, 'Media'),
        ('partners', 7, 'Partners'),
        ('connectivity', 9, 'Con­nectiv­ity'),
    )

    level = models.PositiveSmallIntegerField(choices=LEVELS, default=LEVELS.silver)

    name = models.CharField(max_length=200, unique=True)
    logo = models.FileField(
        null=True, blank=True,
        upload_to='sponsors/pyconcz/',
        help_text='should be SVG'
    )

    description = models.TextField(null=True, blank=True, help_text='Markdown formatted')
    link_url = models.URLField()
    twitter = models.URLField(null=True, blank=True, help_text='full URL')
    facebook = models.URLField(null=True, blank=True, help_text='full URL')

    published = models.BooleanField(default=False)

    class Meta:
        ordering = ['level', 'name']

    def __str__(self):
        return self.name

    @property
    def slug(self):
        return slugify(self.name)

pyconcz/announcements/views.py
from django.template.response import TemplateResponse

from pyconcz.announcements.models import Announcement


def announcement_list(request):
    announcements = Announcement.objects.all()
    return TemplateResponse(
        request, 'announcements/archive.html', {'announcements': announcements}
    )

pyconcz/common/views.py
from datetime import datetime
from django.utils import timezone

import requests
from django.template.response import TemplateResponse
from django.conf import settings

from pyconcz.programme.models import Speaker

requests_session = requests.Session()

_tickets_data_cache = None


def homepage(request):
    keynoters = Speaker.objects.filter(is_public=True, talks__is_keynote=True,
                                       talks__is_backup=False)

    return TemplateResponse(request, 'pages/homepage.html', {'keynoters': keynoters})


def retrieve_tickets_data():
    secret_key = settings.TITO_SECRET_KEY
    account_id = settings.TITO_ACCOUNT_NAME
    event_id = settings.TITO_EVENT_NAME

    releases_api = 'https://api.tito.io/v3/{account_id}/{event_id}/releases'.format(
        account_id=account_id,
        event_id=event_id)

    headers = {
        'Authorization': 'Token token={secret_key}'.format(secret_key=secret_key),
        'Accept': 'application/json',
    }

    res = requests_session.get(releases_api, headers=headers)
    res.raise_for_status()
    releases = res.json()['releases']

    tickets = {
        'vip': {},
        'educational': {},
        'individual': {},
        'company': {},
    }

    ticket_phases = {'early bird': 'early_bird', 'regular': 'regular', 'late bird': 'late_bird'}
    for ticket in releases:
        name = [name for name in tickets if name in ticket['title'].lower()]
        phase = [phase for phase in ticket_phases if phase in ticket['title'].lower()]

        # Calculate how many tickets left for tickets with limited quantity
        if ticket['quantity'] is not None:
            ticket['tickets_left'] = ticket['quantity'] - ticket['tickets_count']

        if name and phase:
            tickets[name[0]][ticket_phases[phase[0]]] = ticket
            # all the regular tickets have the same 'end of sale' date so we extract the first
            if 'last_day_regular' not in tickets and phase[0] == 'regular':
                date_format = '%Y-%m-%dT%H:%M:%S.%f%z'
                # there is no other easy way to process a date with a colon in the timezone. So we
                # remove the colon.
                date_str = ticket['end_at'][:-3] + ticket['end_at'][-2:]
                date = datetime.strptime(date_str, date_format)
                # date which will be displayed on the site, it describes when the sale of regular
                # tickets ends
                tickets['last_day_regular'] = timezone.localtime(date)
                tickets['now'] = timezone.localtime(timezone.now())

    # we need to get the capacity and how many tickets are already sold. We use activities endpoint
    # instead of activity as it has less data and is faster
    activities_api = 'https://api.tito.io/v3/{account_id}/{event_id}/activities'.format(
        account_id=account_id,
        event_id=event_id)

    res = requests_session.get(activities_api, headers=headers)
    res.raise_for_status()
    activities = res.json()

    for activity in activities['activities']:
        # the 'Talks' activity defines our ticket capacity of the conference
        if 'Talks' in activity['name']:
            tickets['sold'] = activity['allocation_count']
            tickets['capacity'] = activity['capacity']
            tickets['left'] = tickets['capacity'] - tickets['sold']
            break

    return tickets


def get_cached_tickets_data():
    global _tickets_data_cache
    if not _tickets_data_cache:
        _tickets_data_cache = retrieve_tickets_data()
    return {**_tickets_data_cache, 'cached': True}


def get_fresh_tickets_data():
    global _tickets_data_cache
    _tickets_data_cache = retrieve_tickets_data()
    return {**_tickets_data_cache, 'cached': False}


def tickets_index(request):
    tickets = get_cached_tickets_data()
    return TemplateResponse(request, 'tickets/tickets.html', {'tickets': tickets})


def tickets_ajax_content(request):
    tickets = get_fresh_tickets_data()
    return TemplateResponse(request, 'tickets/ajax_content.html', {'tickets': tickets})

pyconcz/intermission/views.py
import datetime

from django.template.response import TemplateResponse

from pyconcz.sponsors.models import Sponsor
from pyconcz.programme.models import Slot
from pyconcz.announcements.models import Announcement


def index(request):
    return TemplateResponse(
        request,
        template='intermission/index.html',
        context={
            'interval': int(request.GET.get('interval', 10)) * 1000,
        }
    )


def sponsors(request, level):
    _, val, display = Sponsor.LEVELS.for_constant(level)
    sponsors = Sponsor.objects.filter(published=True, level=val)

    return TemplateResponse(
        request,
        template='intermission/sponsors.html',
        context={
            'sponsors': sponsors,
            'level_name': display,
            'level_slug': level,
        }
    )


def up_next(request, track):
    dt_from = datetime.datetime.now()
    slot = Slot.objects.filter(
        start__gte=dt_from, room=track, object_id__isnull=False
    ).order_by('start').first()

    return TemplateResponse(
        request,
        template='intermission/up_next.html',
        context={
            'slot': slot,
        }
    )


def announcements(request):
    return TemplateResponse(
        request,
        template='intermission/annoucements.html',
        context={
            'announcements': Announcement.objects.filter(is_public=True)[:7],
        }
    )


def slido(request):
    return TemplateResponse(
        request,
        template='intermission/slido.html',
    )

pyconcz/programme/views.py
from django.http import HttpResponse
from django.template.response import TemplateResponse
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_exempt

import requests

from .models import Speaker, Slot, Talk, Workshop
from django.conf import settings


def preview(request):
    speakers = Speaker.objects.prefetch_related('talks', 'workshops').order_by('full_name')

    return TemplateResponse(
        request,
        template='programme/preview.html',
        context={'speakers': speakers}
    )


def talks_list(request):
    nonbackup_talks = Talk.objects.filter(is_backup=False)
    talks = nonbackup_talks.filter(is_public=True, is_backup=False).order_by('order')
    more_to_come = nonbackup_talks.filter(is_public=False).exists()

    return TemplateResponse(
        request,
        template='programme/talks_list.html',
        context={'sessions': talks, 'more_to_come': more_to_come}
    )


def workshops_list(request):
    nonbackup_workshops = Workshop.objects.filter(is_backup=False)
    workshops = nonbackup_workshops.filter(is_public=True, is_backup=False).order_by('order')
    more_to_come = nonbackup_workshops.filter(is_public=False).exists()

    return TemplateResponse(
        request,
        template='programme/workshops_list.html',
        context={'sessions': workshops, 'more_to_come': more_to_come}
    )


@csrf_exempt
def workshops_refresh_tickets(request):
    secret_key = settings.TITO_SECRET_KEY
    account_id = settings.TITO_ACCOUNT_NAME
    event_id = settings.TITO_EVENT_NAME

    releases_api = 'https://api.tito.io/v3/{account_id}/{event_id}/releases'.format(
        account_id=account_id,
        event_id=event_id)

    headers = {
        'Authorization': 'Token token={secret_key}'.format(secret_key=secret_key),
        'Accept': 'application/json',
    }

    requests_session = requests.Session()
    res = requests_session.get(releases_api, headers=headers)
    res.raise_for_status()
    releases = res.json()['releases']

    output = ''

    for ticket in releases:
        if ' Workshop:' in ticket['title']:
            workshop = Workshop.objects.get(tito_id=ticket['slug'])
            workshop.free_tickets_count = ticket['quantity'] - ticket['tickets_count']
            workshop.is_sold_out = ticket['sold_out']
            workshop.save()
            output += 'workshop {id} - registered {registered}, all: {all_tickets}, sold out: {sold_out} ({title})<br>'.format(
                id=workshop.id,
                title=workshop.title,
                registered=ticket['tickets_count'],
                all_tickets=ticket['quantity'],
                sold_out=workshop.is_sold_out
            )

    return HttpResponse(output)


def session_detail(request, type, session_id):
    MODEL_MAP = dict(talk=Talk, workshop=Workshop, sprint=Workshop)
    session = get_object_or_404(MODEL_MAP.get(type), id=session_id, is_public=True, is_backup=False)

    session_slot = Slot.objects.filter(
        content_type__app_label='programme',
        content_type__model=dict(talk='talk', workshop='workshop', sprint='workshop').get(type),
        object_id=session_id,
    ).first()

    session_previous = MODEL_MAP.get(type).objects.filter(
        is_public=True, is_backup=False, order__lt=session.order).order_by('order').last()

    if not session_previous:  # at the first session provide the last one as previous
        session_previous = MODEL_MAP.get(type).objects.filter(
            is_public=True, is_backup=False).order_by('order').last()

    session_next = MODEL_MAP.get(type).objects.filter(
        is_public=True, is_backup=False, order__gt=session.order).order_by('order').first()

    if not session_next:  # at the last session provide the first one as next
        session_next = MODEL_MAP.get(type).objects.filter(
            is_public=True, is_backup=False).order_by('order').first()

    slots_remaining_in_day = Slot.objects.filter(
        content_type__app_label='programme',
        content_type__model__in=['talk', 'workshop', 'utility'],
        start__gte=session_slot.start,
        start__day=session_slot.start.day,
    ).prefetch_related(
        'content_object',
    ).order_by('start', 'room')

    # remove redundant slots
    # note: this expects that sessions and utilities do not mix at the same time
    previous_slot = None
    rows_having_session = 0
    slots = []

    for slot in slots_remaining_in_day:
        if previous_slot and previous_slot.start != slot.start:  # when new row starts
            # did previous row have a session?
            if str(previous_slot.content_type) in ['talk', 'workshop']:
                rows_having_session += 1
                # only current and one future row with sessions is needed
                if rows_having_session >= 2:
                    break
        slots.append(slot)
        previous_slot = slot

    return TemplateResponse(
        request,
        template='programme/{}_detail.html'.format(type),
        context={
            'session': session,
            'other_sessions': {
                'previous': session_previous,
                'next': session_next,
            },
            'session_slot': session_slot,
            'slots': slots,

        }
    )


def talk_frame(request, frame_type, session_id):
    return TemplateResponse(
        request,
        template='programme/talk_frame_{}.html'.format(frame_type),
        context={
            'session': get_object_or_404(Talk, id=session_id),
        }
    )


def other_frame(request, frame_type):
    return TemplateResponse(
        request,
        template='programme/other_frame_{}.html'.format(frame_type)
    )


def schedule(request):
    slots = (
        Slot.objects.filter(
            content_type__app_label='programme',
            content_type__model__in=['talk', 'workshop', 'utility']
        ).prefetch_related(
            'content_object',
        ).order_by('start', 'room')
    )

    return TemplateResponse(
        request,
        template='programme/schedule.html',
        context={
            'slots': slots,
        }
    )

pyconcz/sponsors/views.py
from django.template.response import TemplateResponse

from pyconcz.sponsors.models import Sponsor


def sponsors_list(request):
    items = Sponsor.objects.filter(published=True)
    return TemplateResponse(request, 'sponsors/sponsors_list.html',
                            {'sponsors_list': items})

pyconcz/team/views.py
from django.template import RequestContext
from django.template.response import TemplateResponse

from pyconcz.team.models import Organizer


def team_list(request):
    organizers = Organizer.objects.filter(published=True).order_by('?')

    return TemplateResponse(
        request,
        template='team/organizers_list.html',
        context={
            'organizers': organizers
        }
    )

pyconcz/templates/sponsors/sponsors_homepage.html
{% load sponsors_tags %}

{% get_sponsors as sponsors %}

{% regroup sponsors by get_level_display as sponsors_list %}

{% if sponsors %}
    <section class="pc-sponsors">
        {% for level in sponsors_list %}
            <h2 class="h3 mb-5 text-center {% if forloop.first %}mt-2{% endif %}">{{ level.grouper }}</h2>
            <div class="pc-sponsors-list">
                {% for sponsor in level.list %}
                    <a href="{{ sponsor.link_url }}"
                       class="pc-sponsors-item pc-sponsors-item-{{ level.grouper|lower }}"
                    >
                        {% if sponsor.logo %}
                            <img class="img-fluid pc-img-fluid-svg" src="{{ sponsor.logo.url }}" alt="{{ sponsor.name }}">
                        {% else %}
                            {{ sponsor.name }}
                        {% endif %}
                    </a>
                {% endfor %}
            </div>
        {% endfor %}
    </section>
{% endif %}

pyconcz/templates/sponsors/sponsors_inline.html
{% regroup sponsors by get_level_display as sponsors_list %}

{% if sponsors %}
    <section class="pc-sponsors">
        {% for level in sponsors_list %}
            <h2 class="h3 mb-5 text-center {% if forloop.first %}mt-2{% endif %}">{{ level.grouper }}</h2>
            <div class="pc-sponsors-list">
                {% for sponsor in level.list %}
                    <a href="{{ sponsor.link_url }}"
                       class="pc-sponsors-item pc-sponsors-item-{{ level.grouper|lower }}"
                    >
                        {% if sponsor.logo %}
                            <img class="img-fluid pc-img-fluid-svg" src="{{ sponsor.logo.url }}" alt="{{ sponsor.name }}">
                        {% else %}
                            {{ sponsor.name }}
                        {% endif %}
                    </a>
                {% endfor %}
            </div>
        {% endfor %}
    </section>
{% endif %}

pyconcz/templates/sponsors/sponsors_list.html
{% extends '_layout.html' %}

{% load formatting %}

{% block meta_title %}Sponsors and partners – {{ block.super }}{% endblock %}


{% block main_classes %}bg-white text-dark{% endblock %}


{% block main %}
    <div class="container">
        {% if phases.sponsors != 'details_public' and not user.is_staff %}
            {% include '__404.html' %}
        {% else %}
            {% regroup sponsors_list by get_level_display as sponsor_levels %}


            <h1>Sponsors and partners</h1>

            {% if phases.sponsors != 'details_public' %}
                <div class="alert alert-warning h2 my-5">
                    ⚠️ You see sponsors on this page because you’re logged in.
                    <br>Publicly they’re hidden.
                </div>
            {% endif %}

            <div class="row">
                <div class="col-sm col-md-4">
                    <p class="lead">We’re grateful to companies that help us organize PyCon CZ and allow keeping ticket prices as low as&nbsp;possible.</p>
                </div>
                <div class="col-sm col-md-8">
                    <p>
                        Do you want to sponsor us too?
                        Check out
                        <a href="{% url 'sponsors_offer' %}">our offer</a>
                        or <a href="mailto:info@pycon.cz">contact&nbsp;us</a>.
                    </p>
                </div>
            </div>

            {% for level in sponsor_levels %}
                <h2 class="mt-md-6">{{ level.grouper }}</h2>
                {% for sponsor in level.list %}
                    <div class="row {% if not sponsor.description %}align-items-center mt-4 mb-5{% endif %}" id="sponsor-{{ sponsor.slug }}">

                        <div class="col-12 col-sm-8 col-md-4 col-lg-3 mt-5 mt-sm-4 {% if not sponsor.description %}mb-3 mb-sm-4{% endif %}">
                            {% if sponsor.logo %}
                                <a href="{{ sponsor.link_url }}" class="d-block">
                                    <img
                                        class="pc-sponsor-detail-logo img-fluid pc-img-fluid-svg"
                                        src="{{ sponsor.logo.url }}"
                                        alt="{{ sponsor.name }}"
                                    >
                                </a>
                            {% endif %}
                        </div>

                        <div class="col-12 col-md mt-sm-2 mb-sm-4">
                            <h3 class="sponsor-detail-heading {% if not sponsor.description %}d-none d-md-block{% endif %}">
                                {{ sponsor.name }}
                            </h3>
                            {{ sponsor.description|markdown }}

                            {% if user.is_staff and sponsor.description %}
                                <div class="alert alert-info">
                                    ℹ️ {{ sponsor.description|markdown|striptags|wordcount }} words
                                </div>
                            {% endif %}
                        </div>

                    </div>
                {% endfor %}
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}