pyconcz/common/urls.py
from django.conf.urls import url

from pyconcz.common.views import tickets_index, tickets_ajax_content


urlpatterns = [
    url('^$', tickets_index, name='tickets'),
    url('^ajax-content$', tickets_ajax_content, name='tickets_ajax_content'),
]

pyconcz/intermission/urls.py
from django.conf.urls import url

from pyconcz.intermission import views


urlpatterns = [
    url('^$', views.index, name='cycle_all'),
    url('^sponsors/(?P<level>[\w\-]+)/$', views.sponsors, name='sponsors'),
    url('^annoucements/$', views.announcements, name='annoucements'),
    url('^up-next/(?P<track>\d+)/$', views.up_next, name='up_next'),
    url('^slido/$', views.slido, name='slido'),
]

pyconcz/sponsors/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from pyconcz.sponsors.views import sponsors_list


urlpatterns = [
    url('^$', sponsors_list, name='sponsors_list'),

    url(r'^offer/$',
        TemplateView.as_view(template_name='pages/sponsors_offer.html'),
        name='sponsors_offer'),
]

pyconcz/team/urls.py
from django.conf.urls import url

from pyconcz.team.views import team_list


urlpatterns = [
    url('^$', team_list, name='team_list'),
]

pyconcz/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView

from pyconcz.common.views import homepage

prefixed_urlpatterns = [
    url(r'^$', homepage, name='homepage'),
    url(r'^programme/', include('pyconcz.programme.urls')),
    url(r'^team/', include('pyconcz.team.urls')),
    url(r'^proposals/', include('pyconcz.proposals.urls')),
    url(r'^announcements/', include('pyconcz.announcements.urls')),
    url(r'^sponsors/', include('pyconcz.sponsors.urls')),
    url(r'^tickets/', include('pyconcz.common.urls')),
    url(r'^intermission/', include('pyconcz.intermission.urls', namespace='intermission')),

    # static pages
    url(r'^coc/$', TemplateView.as_view(template_name='pages/coc.html'), name='coc'),
    url(r'^privacy-policy/$', TemplateView.as_view(template_name='pages/privacy_policy.html'), name='privacy_policy'),
    url(r'^ostrava/$', TemplateView.as_view(template_name='pages/ostrava.html'), name='city'),
    url(r'^venue/$', TemplateView.as_view(template_name='pages/venue.html'), name='venue'),
    url(r'^board-game-night/$', TemplateView.as_view(template_name='pages/board_game_night.html'), name='board_game_night'),
    url(r'^workshop-leaders-info/$', TemplateView.as_view(template_name='pages/workshop_leaders_info.html'), name='workshop_leaders_info'),
    url(r'^pattern-lib/$', TemplateView.as_view(template_name='pages/pattern_lib.html'), name='pattern_lib'),

    # redirects to external websites
    url(r'^video/$', RedirectView.as_view(url='https://www.youtube.com/watch?v=kL2gmhs0irI')),


    # static pages
    # url(r'^transparency-report/$', TemplateView.as_view(template_name='pages/transparency.html'), name='about_transparency'),

    # old urls redirect (delete when changing 2019 to 2020)
    url(r'^about/code/?$', RedirectView.as_view(url='/2019/coc/', permanent=True)),
    url(r'^about/privacy/?$', RedirectView.as_view(url='/2019/privacy-policy/', permanent=True)),
    url(r'^about/team/?$', RedirectView.as_view(url='/2019/team/', permanent=True)),
]

urlpatterns = (
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        [
            url(r'^coc/$', RedirectView.as_view(url='/2019/coc/')),
            url(r'^2019/', include(prefixed_urlpatterns)),
            url(r'^admin/', include(admin.site.urls)),
            url(r'^$', RedirectView.as_view(url='/2019/')),
        ]
)

pyconcz/programme/models.py
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.urls import reverse


class Speaker(models.Model):
    full_name = models.CharField(max_length=200)
    bio = models.TextField()
    short_bio = models.TextField('Short bio', blank=True, help_text='For keynote speakers')
    twitter = models.CharField(max_length=255, blank=True)
    github = models.CharField(max_length=255, blank=True)
    email = models.EmailField()
    photo = models.ImageField(upload_to='programme/speakers/')
    talks = models.ManyToManyField('Talk', blank=True, related_name='talk_speakers')
    workshops = models.ManyToManyField('Workshop', blank=True, related_name='ws_speakers')
    display_position = models.PositiveSmallIntegerField(default=0, help_text='sort order on frontend displays')
    is_public = models.BooleanField(default=True)

    class Meta:
        ordering = ('display_position', 'full_name',)

    def __str__(self):
        return self.full_name

    def _talkws_export(self, type_):
        qs = self.talks.all() if type_ == 'talk' else self.workshops.all()
        return '\n'.join([
            '%s | %s' % (
                t.title, 'https://cz.pycon.org'
                + reverse('session_detail', kwargs={'type': type_, 'talk_id': t.id}),
            )
            for t in qs
        ])

    def talks_export(self):
        return self._talkws_export('talk')

    def workshops_export(self):
        return self._talkws_export('workshop')


class Talk(models.Model):
    DIFFICULTY = (
        ('beginner', 'Beginner'),
        ('advanced', 'Advanced'),
    )

    LANGUAGES = (
        ('en', 'English (preferred)'),
        ('cs', 'Czechoslovak'),
    )

    type = 'talk'  # for symmetry with workshops/sprints
    order = models.SmallIntegerField(unique=True, help_text='display order on front end, has to be unique')
    title = models.CharField(max_length=200)
    og_image = models.ImageField(upload_to='programme/talks/', null=True, blank=True, help_text='og:image (social media image) 1200×630 pixels')
    abstract = models.TextField()
    language = models.CharField(max_length=2, choices=LANGUAGES, default='en')
    difficulty = models.CharField(max_length=10, choices=DIFFICULTY, default='beginner')
    video_id = models.CharField(max_length=100, default='', blank=True, help_text='youtube')
    is_backup = models.BooleanField(default=False, blank=True)
    is_keynote = models.BooleanField(default=False, blank=True)
    is_public = models.BooleanField(default=False, blank=True)
    in_data_track = models.BooleanField('PyData Track', default=False, blank=True)
    private_note = models.TextField(default='', blank=True, help_text='DO NOT SHOW ON WEBSITE')

    class Meta:
        ordering = ('order',)

    def __str__(self):
        return self.title

    @property
    def speakers(self):
        return self.talk_speakers.all()

    @property
    def speakers_display(self):
        return '; '.join(map(str, self.speakers))

    @property
    def video_embed_url(self):
        return 'https://www.youtube.com/embed/' + self.video_id


class Workshop(models.Model):
    DIFFICULTY = (
        ('beginner', 'Beginner'),
        ('advanced', 'Advanced'),
    )

    TYPE = (
        ('workshop', 'Workshop'),
        ('sprint', 'Sprint'),
    )

    LENGTH = (
        ('1h', '1 hour'),
        ('2h', '2 hours'),
        ('3h', '3 hours'),
        ('1d', 'Full day (most sprints go here!)'),
        ('xx', 'Something else! (Please leave a note in the abstract!)')
    )

    LANGUAGES = (
        ('en', 'English (preferred)'),
        ('cs', 'Czech/Slovak'),
    )

    REGISTRATION = (
        ('without', 'Without'),
        ('free', 'Free'),
        ('paid', 'Paid'),
    )

    type = models.CharField(max_length=10, choices=TYPE, default='sprint')
    order = models.SmallIntegerField(unique=True, help_text='display order on front end, has to be unique')
    title = models.CharField(max_length=200, verbose_name='Title')
    og_image = models.ImageField(upload_to='programme/workshops/', null=True, blank=True, help_text='og:image (social media image) 1200×630 pixels')
    abstract = models.TextField()
    requirements = models.TextField('What should attendees bring, install and know?', default='', blank=True, help_text='Include even the most obvious stuff: laptops, git, python')
    language = models.CharField(max_length=2, choices=LANGUAGES, default='en')
    difficulty = models.CharField(max_length=10, choices=DIFFICULTY, default='beginner', )
    length = models.CharField(max_length=2, choices=LENGTH, blank=True, )
    attendee_limit = models.PositiveSmallIntegerField('Atendee limit', default=False, blank=True, help_text='Maximum number of attendees allowed')
    tito_id = models.SlugField('Ticket ID in ti.to', null=True, blank=True, help_text='Tickets are called releases in API')
    free_tickets_count = models.PositiveSmallIntegerField(default=0, help_text='Count of free tickets (from API)')
    registration = models.CharField(max_length=10, choices=REGISTRATION, default='free', blank='free')
    is_backup = models.BooleanField(default=False, blank=True)
    is_public = models.BooleanField(default=False, blank=True)
    in_data_track = models.BooleanField('PyData Track', default=False, blank=True)
    is_sold_out = models.BooleanField('Sold out', default=False, blank=True)
    private_note = models.TextField(default='', blank=True, help_text='DO NOT SHOW ON WEBSITE')

    class Meta:
        ordering = ('order',)

    def __str__(self):
        return self.title

    @property
    def speakers(self):
        return self.ws_speakers.all()

    @property
    def speakers_display(self):
        return '; '.join(map(str, self.speakers))


class Slot(models.Model):
    start = models.DateTimeField()
    content_type = models.ForeignKey(ContentType, null=True, blank=True, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField(null=True, blank=True)
    content_object = GenericForeignKey('content_type', 'object_id')
    room = models.PositiveSmallIntegerField(choices=settings.ALL_ROOMS)
    end = models.DateTimeField()

    def __str__(self):
        start = self.start.strftime('%d/%m/%y %H:%M')
        end = self.end.strftime('%d/%m/%y %H:%M')
        return '%s: %s FROM %s TO %s IN %s' % (
            self.content_type, self.content_object, start, end, self.room_name)

    @property
    def room_name(self):
        return settings.ALL_ROOMS_DICT.get(self.room)

    class Meta:
        ordering = ('start', 'room',)


class Utility(models.Model):
    title = models.CharField(max_length=200, verbose_name='Title')
    description = models.TextField(blank=True, null=True)
    url = models.CharField(max_length=255, blank=True, null=True)
    is_streamed = models.BooleanField('Is streamed to other rooms', default=False, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Utility'
        verbose_name_plural = 'Utilities'
        ordering = ('title', 'id',)

pyconcz/announcements/views.py
from django.template.response import TemplateResponse

from pyconcz.announcements.models import Announcement


def announcement_list(request):
    announcements = Announcement.objects.all()
    return TemplateResponse(
        request, 'announcements/archive.html', {'announcements': announcements}
    )

pyconcz/common/views.py
from datetime import datetime
from django.utils import timezone

import requests
from django.template.response import TemplateResponse
from django.conf import settings

from pyconcz.programme.models import Speaker

requests_session = requests.Session()

_tickets_data_cache = None


def homepage(request):
    keynoters = Speaker.objects.filter(is_public=True, talks__is_keynote=True,
                                       talks__is_backup=False)

    return TemplateResponse(request, 'pages/homepage.html', {'keynoters': keynoters})


def retrieve_tickets_data():
    secret_key = settings.TITO_SECRET_KEY
    account_id = settings.TITO_ACCOUNT_NAME
    event_id = settings.TITO_EVENT_NAME

    releases_api = 'https://api.tito.io/v3/{account_id}/{event_id}/releases'.format(
        account_id=account_id,
        event_id=event_id)

    headers = {
        'Authorization': 'Token token={secret_key}'.format(secret_key=secret_key),
        'Accept': 'application/json',
    }

    res = requests_session.get(releases_api, headers=headers)
    res.raise_for_status()
    releases = res.json()['releases']

    tickets = {
        'vip': {},
        'educational': {},
        'individual': {},
        'company': {},
    }

    ticket_phases = {'early bird': 'early_bird', 'regular': 'regular', 'late bird': 'late_bird'}
    for ticket in releases:
        name = [name for name in tickets if name in ticket['title'].lower()]
        phase = [phase for phase in ticket_phases if phase in ticket['title'].lower()]

        # Calculate how many tickets left for tickets with limited quantity
        if ticket['quantity'] is not None:
            ticket['tickets_left'] = ticket['quantity'] - ticket['tickets_count']

        if name and phase:
            tickets[name[0]][ticket_phases[phase[0]]] = ticket
            # all the regular tickets have the same 'end of sale' date so we extract the first
            if 'last_day_regular' not in tickets and phase[0] == 'regular':
                date_format = '%Y-%m-%dT%H:%M:%S.%f%z'
                # there is no other easy way to process a date with a colon in the timezone. So we
                # remove the colon.
                date_str = ticket['end_at'][:-3] + ticket['end_at'][-2:]
                date = datetime.strptime(date_str, date_format)
                # date which will be displayed on the site, it describes when the sale of regular
                # tickets ends
                tickets['last_day_regular'] = timezone.localtime(date)
                tickets['now'] = timezone.localtime(timezone.now())

    # we need to get the capacity and how many tickets are already sold. We use activities endpoint
    # instead of activity as it has less data and is faster
    activities_api = 'https://api.tito.io/v3/{account_id}/{event_id}/activities'.format(
        account_id=account_id,
        event_id=event_id)

    res = requests_session.get(activities_api, headers=headers)
    res.raise_for_status()
    activities = res.json()

    for activity in activities['activities']:
        # the 'Talks' activity defines our ticket capacity of the conference
        if 'Talks' in activity['name']:
            tickets['sold'] = activity['allocation_count']
            tickets['capacity'] = activity['capacity']
            tickets['left'] = tickets['capacity'] - tickets['sold']
            break

    return tickets


def get_cached_tickets_data():
    global _tickets_data_cache
    if not _tickets_data_cache:
        _tickets_data_cache = retrieve_tickets_data()
    return {**_tickets_data_cache, 'cached': True}


def get_fresh_tickets_data():
    global _tickets_data_cache
    _tickets_data_cache = retrieve_tickets_data()
    return {**_tickets_data_cache, 'cached': False}


def tickets_index(request):
    tickets = get_cached_tickets_data()
    return TemplateResponse(request, 'tickets/tickets.html', {'tickets': tickets})


def tickets_ajax_content(request):
    tickets = get_fresh_tickets_data()
    return TemplateResponse(request, 'tickets/ajax_content.html', {'tickets': tickets})

pyconcz/intermission/views.py
import datetime

from django.template.response import TemplateResponse

from pyconcz.sponsors.models import Sponsor
from pyconcz.programme.models import Slot
from pyconcz.announcements.models import Announcement


def index(request):
    return TemplateResponse(
        request,
        template='intermission/index.html',
        context={
            'interval': int(request.GET.get('interval', 10)) * 1000,
        }
    )


def sponsors(request, level):
    _, val, display = Sponsor.LEVELS.for_constant(level)
    sponsors = Sponsor.objects.filter(published=True, level=val)

    return TemplateResponse(
        request,
        template='intermission/sponsors.html',
        context={
            'sponsors': sponsors,
            'level_name': display,
            'level_slug': level,
        }
    )


def up_next(request, track):
    dt_from = datetime.datetime.now()
    slot = Slot.objects.filter(
        start__gte=dt_from, room=track, object_id__isnull=False
    ).order_by('start').first()

    return TemplateResponse(
        request,
        template='intermission/up_next.html',
        context={
            'slot': slot,
        }
    )


def announcements(request):
    return TemplateResponse(
        request,
        template='intermission/annoucements.html',
        context={
            'announcements': Announcement.objects.filter(is_public=True)[:7],
        }
    )


def slido(request):
    return TemplateResponse(
        request,
        template='intermission/slido.html',
    )

pyconcz/sponsors/views.py
from django.template.response import TemplateResponse

from pyconcz.sponsors.models import Sponsor


def sponsors_list(request):
    items = Sponsor.objects.filter(published=True)
    return TemplateResponse(request, 'sponsors/sponsors_list.html',
                            {'sponsors_list': items})

pyconcz/team/views.py
from django.template import RequestContext
from django.template.response import TemplateResponse

from pyconcz.team.models import Organizer


def team_list(request):
    organizers = Organizer.objects.filter(published=True).order_by('?')

    return TemplateResponse(
        request,
        template='team/organizers_list.html',
        context={
            'organizers': organizers
        }
    )

pyconcz/templates/intermission/annoucements.html
{% load formatting %}
{% load static %}

<div class="pc-intermission-content">
    {% if announcements %}
        <div class="mt-6">
            {% for announcement in announcements %}
                <div class="pc-intermission-announcement display-{{ announcement.font_size }} py-5">
                    {{ announcement.message|markdown }}
                </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="d-flex h-100 pb-5">
            <img class="pc-img-fluid-svg w-100" src="{% static 'img/pycon19-logo.svg' %}" alt="">
        </div>
    {% endif %}
</div>

pyconcz/templates/intermission/index.html
{% extends '_base.html' %}


{% load static %}


{% block meta_title %}Intermission – {{ block.super }}{% endblock %}


{% block body_extras %}style="overflow:hidden;"{% endblock %}


{% block body %}
    <main role="main" class="pc-intermission" id="intermission-content"></main>
{% endblock %}


{% block after_scripts_loaded %}
    <script>
        $(document).ready(function(){
            var urls = [
                '{% url 'intermission:annoucements' %}',
                '{% url 'intermission:slido' %}',

                '{% url 'intermission:up_next' track=1 %}',
                '{% url 'intermission:up_next' track=2 %}',

                '{% url 'intermission:sponsors' level='platinum' %}',

                '{% url 'intermission:annoucements' %}',
                '{% url 'intermission:slido' %}',

                '{% url 'intermission:sponsors' level='gold' %}',

                '{% url 'intermission:up_next' track=1 %}',
                '{% url 'intermission:up_next' track=2 %}',

                '{% url 'intermission:sponsors' level='silver' %}',

                '{% url 'intermission:annoucements' %}',
                '{% url 'intermission:slido' %}',

                '{% url 'intermission:sponsors' level='bronze' %}',

                '{% url 'intermission:up_next' track=1 %}',
                '{% url 'intermission:up_next' track=2 %}',

                '{% url 'intermission:sponsors' level='partners' %}',

            ];

            function cycle(delay, f, xs){
                var now = -1;
                var active = true;
                var show_current = function(){
                    f(xs[now]);
                };
                var next = function(){
                    now++;
                    if (now >= xs.length) now = 0;
                    show_current();
                };
                var prev = function(){
                    now--;
                    if (now < 0) now = xs.length - 1;
                    show_current();
                };
                var run = function(){
                    if (active) next();
                    setTimeout(run, delay);
                };
                run();

                function handle_keydown(event){
                    if (['ArrowDown', 'ArrowLeft', 'PageDown'].includes(event.key)){
                        active = false;
                        next();
                    }
                    if (['ArrowUp', 'ArrowRight', 'PageUp'].includes(event.key)){
                        active = false;
                        prev();
                    }
                    if ([' '].includes(event.key)){
                        active = true;
                        show_current();
                    }
                }

                document.addEventListener('keydown', handle_keydown, false);
            }

            function fetch_content(url){
                $.get(url, function(data){
                    $('#intermission-content').hide().html(data).fadeIn(300);
                });
            }

            cycle({{ interval }}, fetch_content, urls);
        });
    </script>

{% endblock %}

pyconcz/templates/intermission/slido.html
{% load formatting %}

<div class="pc-intermission-content">
    <div class="d-flex flex-wrap h-100 align-content-around pb-7">
        <p class="display-1 text-center w-100">
            Ask speakers on <strong>slido.com</strong> with&nbsp;hashtag&nbsp;<strong>#pyconcz</strong>&nbsp;💬️
        </p>
        <p class="display-1 text-center w-100">
            Join conference attendee Slack 👋️
            <br><strong>bit.ly/pycz19slack</strong>
        </p>
    </div>
</div>

pyconcz/templates/intermission/sponsors.html
<div class="pc-intermission-content bg-white text-dark">
    <h1 class="pc-intermission-heading display-1 mt-6">
        Our <strong>{{ level_name }}</strong>
        {% if level_slug != 'partners' %}sponsor{{ sponsors|pluralize:'s' }}{% endif %}
    </h1>

    <div class="pc-intermission-sponsors">
        {% for sponsor in sponsors %}
            <div class="pc-intermission-sponsors-item pc-intermission-sponsors-item-{{ level_name|lower }}">
                <img class="pc-img-fluid-svg pc-intermission-sponsors-logo pc-intermission-sponsors-logo-{{ level_name|lower }}" src="{{ sponsor.logo.url }}" alt="{{ sponsor.name }}">
            </div>
        {% endfor %}
    </div>
</div>

pyconcz/templates/intermission/up_next.html
{% load formatting %}

<div class="pc-intermission-content">
    <h1 class="display-1 mt-6">
        Next up in
        <strong {% if slot.room == 2 %}class=""{% endif %}>{{ slot.get_room_display }}</strong>
        from {{ slot.start|date:'H:i' }}
    </h1>

    {% if slot.content_object.speakers %}
        <div style="width:45%; transform: scale(2.26);transform-origin: 0 0;">
            {% for speaker in slot.content_object.speakers %}
                {% include 'programme/__speaker_detail.html' with type='intermission' odd=forloop.counter|divisibleby:'2' %}
            {% endfor %}
        </div>
    {% else %}
        <h2 class="display-1 text-primary pc-font-weight-medium-mono">
            {{ slot.content_object.title }}
        </h2>
        {% if slot.content_object.is_keynote or slot.content_object.title == 'Welcome to PyCon CZ' or slot.content_object.title == 'Lightning talks' or slot.content_object.title == 'Closing ceremony' %} {# todo: refactor #}
            <p class="display-3">also streamed to Club</p>
        {% endif %}
    {% endif %}
</div>