pyconcz/common/urls.py
from django.conf.urls import url

from pyconcz.common.views import tickets_index, tickets_ajax_content


urlpatterns = [
    url('^$', tickets_index, name='tickets'),
    url('^ajax-content$', tickets_ajax_content, name='tickets_ajax_content'),
]

pyconcz/sponsors/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from pyconcz.sponsors.views import sponsors_list


urlpatterns = [
    url('^$', sponsors_list, name='sponsors_list'),

    url(r'^offer/$',
        TemplateView.as_view(template_name='pages/sponsors_offer.html'),
        name='sponsors_offer'),
]

pyconcz/team/urls.py
from django.conf.urls import url

from pyconcz.team.views import team_list


urlpatterns = [
    url('^$', team_list, name='team_list'),
]

pyconcz/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView

from pyconcz.common.views import homepage

prefixed_urlpatterns = [
    url(r'^$', homepage, name='homepage'),
    url(r'^programme/', include('pyconcz.programme.urls')),
    url(r'^team/', include('pyconcz.team.urls')),
    url(r'^proposals/', include('pyconcz.proposals.urls')),
    url(r'^announcements/', include('pyconcz.announcements.urls')),
    url(r'^sponsors/', include('pyconcz.sponsors.urls')),
    url(r'^tickets/', include('pyconcz.common.urls')),
    url(r'^intermission/', include('pyconcz.intermission.urls', namespace='intermission')),

    # static pages
    url(r'^coc/$', TemplateView.as_view(template_name='pages/coc.html'), name='coc'),
    url(r'^privacy-policy/$', TemplateView.as_view(template_name='pages/privacy_policy.html'), name='privacy_policy'),
    url(r'^ostrava/$', TemplateView.as_view(template_name='pages/ostrava.html'), name='city'),
    url(r'^venue/$', TemplateView.as_view(template_name='pages/venue.html'), name='venue'),
    url(r'^board-game-night/$', TemplateView.as_view(template_name='pages/board_game_night.html'), name='board_game_night'),
    url(r'^workshop-leaders-info/$', TemplateView.as_view(template_name='pages/workshop_leaders_info.html'), name='workshop_leaders_info'),
    url(r'^pattern-lib/$', TemplateView.as_view(template_name='pages/pattern_lib.html'), name='pattern_lib'),

    # redirects to external websites
    url(r'^video/$', RedirectView.as_view(url='https://www.youtube.com/watch?v=kL2gmhs0irI')),


    # static pages
    # url(r'^transparency-report/$', TemplateView.as_view(template_name='pages/transparency.html'), name='about_transparency'),

    # old urls redirect (delete when changing 2019 to 2020)
    url(r'^about/code/?$', RedirectView.as_view(url='/2019/coc/', permanent=True)),
    url(r'^about/privacy/?$', RedirectView.as_view(url='/2019/privacy-policy/', permanent=True)),
    url(r'^about/team/?$', RedirectView.as_view(url='/2019/team/', permanent=True)),
]

urlpatterns = (
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        [
            url(r'^coc/$', RedirectView.as_view(url='/2019/coc/')),
            url(r'^2019/', include(prefixed_urlpatterns)),
            url(r'^admin/', include(admin.site.urls)),
            url(r'^$', RedirectView.as_view(url='/2019/')),
        ]
)

pyconcz/proposals/models.py
from django.conf import settings
from django.contrib.contenttypes.fields import (
    GenericForeignKey, GenericRelation)
from django.contrib.contenttypes.models import ContentType
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import Aggregate
from django.utils.timezone import now


class Ranking(models.Model):
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    class Meta:
        unique_together = ('content_type', 'object_id')

    def get_user_score(self, user):
        return self.scores.filter(user=user).first()


class Score(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    ranking = models.ForeignKey(Ranking, related_name='scores')

    value = models.DecimalField(max_digits=2,
                                decimal_places=1,
                                null=True,
                                blank=True,
                                help_text='4 = Must have!, 3 = Interesting talk, '
                                          '2 = Meh, 1 = Definitely not!, '
                                          'blank value = No score (f.e. your proposal); '
                                          'you can also use decimals',
                                validators=[
                                    MinValueValidator(1),
                                    MaxValueValidator(4)
                                ]
                                )
    note = models.TextField(
        default='', blank=True,
        help_text='Only you can see this'
    )

    class Meta:
        permissions = (
            ('can_add_score', 'Can add score'),
        )

    def __str__(self):
        return ' '.join([
            str(self.value),
            '({})'.format(self.note) if self.note else '']
        )


class EntryBase(models.Model):
    # Private notes (for reviewers only)
    note = models.TextField(blank=True, default='')
    date = models.DateTimeField(default=now)
    rankings = GenericRelation(Ranking)
    accepted = models.BooleanField(default=False, blank=True)

    class Meta:
        abstract = True

    def get_ranking(self):
        return self.rankings.all()[0]


class Talk(EntryBase):
    DIFFICULTY = (
        ('beginner', 'Beginner  (suitable for everyone)'),
        ('advanced', 'Advanced  (requires a higher level of Python knowledge)'),
    )

    LANGUAGES = (
        ('en', 'English (preferred at PyCon CZ)'),
        ('cs', 'Czech or Slovak'),
    )

    # Public speaker info
    full_name = models.CharField(
        max_length=200, verbose_name='What’s your name?',
        help_text='Use a name that you’re comfortable with, or a nickname.'
                  '\nFeel free to use Unicode characters.'
    )
    email = models.EmailField(
        verbose_name='Your email address',
        help_text='We’ll keep it secret and use only to contact you.'
    )
    bio = models.TextField(
        verbose_name='Why are you the right person to talk about the topic you chose?'
                     ' (between 50 and 90 words)',
        help_text='Tell your audience in first person (e.g. „I write…“ not „Alex writes…“ ) '
                  'about anything relevant about you, whether it’s your background, '
                  'education, experience, current or former employer, hobbies '
                  'or opensource software you maintain.'
                  '\nYou can of course include anything fun or quirky about yourself.'
    )
    referral_link = models.URLField(
        default='', blank=True,
        verbose_name='Got a video?',
        help_text='If you have a link to a publicly available recording of you'
                  ' giving a talk or leading a workshop, you can paste the link here. '
                  '\nWill be used in the decision process.'
    )
    twitter = models.CharField(
        max_length=255, blank=True,
        verbose_name='Your Twitter handle', help_text='Optional. Write it without the @.'
    )
    github = models.URLField(
        default='', blank=True,
        verbose_name='Your public code repository (GitHub, GitLab, …)', help_text='Optional. The whole URL.'
    )
    photo = models.ImageField(
        upload_to='proposals/pyconcz2019/talks/',
        verbose_name='Your photo (not an illustration nor avatar)',
        help_text='If you don’t have a photo according to specs below, we will ask you for one if your talk is selected.'
                  '\nIdeal photo is:'
                  '\n– as large as possible (please no 128 × 128 px,'
                  ' there is no upper limit, even 1000 × 1000 px isn’t too much),'
                  '\n– as uncompressed as possible (JPEGs are ok),'
                  '\n– doesn’t show other people'
                  '\n– is a head shot (not you in front of a pyramid)'
                  '\n– is not black and white and has no “creative filters” applied.'
                  '\nWe might crop it and change contrast, brightness etc. to fit PyCon CZ visual style.'
    )

    # Public talk info
    title = models.CharField(
        max_length=200, verbose_name='Title of your talk',
        help_text='The shortest way to say what it will be about.'
    )
    abstract = models.TextField(
        verbose_name='Tell the audience more about your talk in 1–3 paragraphs (90–200 words total)',
        help_text='Try to write as if you’re talking to a real person.'
                  '\nUse plain text or Markdown.'
                  '\n\nYou might want to follow these guidelines:'
                  '\nFirst introduce the problem your talk will bring a solution to.'
                  '\nThen explain why it’s a problem worth solving.'
                  '\nUse the last paragraph to tell your audience what is your '
                  'approach to solving it.'

    )
    language = models.CharField(
        max_length=2, verbose_name='Talk language',
        choices=LANGUAGES, default='en',
        help_text='English is preferred, but if you feel uncomfortable with it,'
                  ' you can give your talk in Czech or Slovak'
    )
    difficulty = models.CharField(
        max_length=10, verbose_name='Talk difficulty',
        choices=DIFFICULTY, default='beginner'
    )
    needs_finaid = models.BooleanField(
        default=False,
        verbose_name='I need financial aid to make this talk possible',
        help_text='Covering travel or accommodation costs etc.'
                  '\nPlease specify this here and now, otherwise we might'
                  ' not be able to grant you the aid.'
    )
    finaid_details = models.TextField(
        null=True, blank=True,
        verbose_name='Details about required financial aid',
        help_text='Please state explicitly:'
                  '\n1) why you need it,'
                  '\n2) what for and'
                  '\n3) how much in EUR or CZK.'
                  '\nIf you require aid for more items (accommodation, travel costs etc.) '
                  'please state the amount for each item.'
    )
    final_note = models.TextField(
        null=True, blank=True,
        verbose_name='Anything else you want to tell us?'
    )
    gdpr_consent = models.BooleanField(
        default=False, blank=False,
        verbose_name='I have read and agree to the PyCon CZ Privacy Policy and Code of Conduct',
        # Please change this, if you know how to do it better (place HTML tags to verbose_name?)
        help_text='<a href="/2019/about/privacy/">Privacy Policy</a> and <a href="/2019/about/code/">Code of Conduct</a>',
    )
    is_backup = models.BooleanField(default=False)
    is_keynote = models.BooleanField(default=False)

    def __str__(self):
        return '{s.full_name} - {s.title}'.format(s=self)


class Workshop(EntryBase):
    DIFFICULTY = (
        ('beginner', 'Beginner  (suitable for everyone)'),
        ('advanced', 'Advanced  (requires a higher level of Python knowledge)'),
    )

    TYPE = (
        ('workshop', 'Workshop'),
        ('sprint', 'Sprint'),
    )

    LENGTH = (
        ('1h', '1 hour'),
        ('2h', '2 hours'),
        ('3h', '3 hours'),
        ('1d', 'Full day (most sprints go here!)'),
        ('xx', 'Something else! (Please leave a note in the abstract)')
    )

    LANGUAGES = (
        ('en', 'English (preferred at PyCon CZ)'),
        ('cs', 'Czech or Slovak'),
    )

    # Public speaker info
    full_name = models.CharField(
        max_length=200, verbose_name='What’s your name?',
        help_text='Use a name that you’re comfortable with, or a nickname.'
                  '\nFeel free to use Unicode characters.'
    )
    email = models.EmailField(
        verbose_name='Your email address',
        help_text='We’ll keep it secret and use only to contact you.'
    )
    bio = models.TextField(
        verbose_name='Why are you the right person to lead a workshop about the topic you chose?'
                     ' (between 50 and 90 words)',
        help_text='Tell your audience in first person (e.g. „I write…“ not „Alex writes…“ ) '
                  'about anything relevant about you, whether it’s your background, '
                  'education, experience, current or former employer, hobbies '
                  'or opensource software you maintain.'
                  '\nYou can of course include anything fun or quirky about yourself.'
    )
    referral_link = models.URLField(
        default='', blank=True,
        verbose_name='Got a video?',
        help_text='If you have a link to a publicly available recording of you'
                  ' giving a talk or leading a workshop, you can paste the link'
                  ' here. Will be used in the decision process.'
    )
    twitter = models.CharField(
        max_length=255, blank=True,

pyconcz/announcements/views.py
from django.template.response import TemplateResponse

from pyconcz.announcements.models import Announcement


def announcement_list(request):
    announcements = Announcement.objects.all()
    return TemplateResponse(
        request, 'announcements/archive.html', {'announcements': announcements}
    )

pyconcz/common/views.py
from datetime import datetime
from django.utils import timezone

import requests
from django.template.response import TemplateResponse
from django.conf import settings

from pyconcz.programme.models import Speaker

requests_session = requests.Session()

_tickets_data_cache = None


def homepage(request):
    keynoters = Speaker.objects.filter(is_public=True, talks__is_keynote=True,
                                       talks__is_backup=False)

    return TemplateResponse(request, 'pages/homepage.html', {'keynoters': keynoters})


def retrieve_tickets_data():
    secret_key = settings.TITO_SECRET_KEY
    account_id = settings.TITO_ACCOUNT_NAME
    event_id = settings.TITO_EVENT_NAME

    releases_api = 'https://api.tito.io/v3/{account_id}/{event_id}/releases'.format(
        account_id=account_id,
        event_id=event_id)

    headers = {
        'Authorization': 'Token token={secret_key}'.format(secret_key=secret_key),
        'Accept': 'application/json',
    }

    res = requests_session.get(releases_api, headers=headers)
    res.raise_for_status()
    releases = res.json()['releases']

    tickets = {
        'vip': {},
        'educational': {},
        'individual': {},
        'company': {},
    }

    ticket_phases = {'early bird': 'early_bird', 'regular': 'regular', 'late bird': 'late_bird'}
    for ticket in releases:
        name = [name for name in tickets if name in ticket['title'].lower()]
        phase = [phase for phase in ticket_phases if phase in ticket['title'].lower()]

        # Calculate how many tickets left for tickets with limited quantity
        if ticket['quantity'] is not None:
            ticket['tickets_left'] = ticket['quantity'] - ticket['tickets_count']

        if name and phase:
            tickets[name[0]][ticket_phases[phase[0]]] = ticket
            # all the regular tickets have the same 'end of sale' date so we extract the first
            if 'last_day_regular' not in tickets and phase[0] == 'regular':
                date_format = '%Y-%m-%dT%H:%M:%S.%f%z'
                # there is no other easy way to process a date with a colon in the timezone. So we
                # remove the colon.
                date_str = ticket['end_at'][:-3] + ticket['end_at'][-2:]
                date = datetime.strptime(date_str, date_format)
                # date which will be displayed on the site, it describes when the sale of regular
                # tickets ends
                tickets['last_day_regular'] = timezone.localtime(date)
                tickets['now'] = timezone.localtime(timezone.now())

    # we need to get the capacity and how many tickets are already sold. We use activities endpoint
    # instead of activity as it has less data and is faster
    activities_api = 'https://api.tito.io/v3/{account_id}/{event_id}/activities'.format(
        account_id=account_id,
        event_id=event_id)

    res = requests_session.get(activities_api, headers=headers)
    res.raise_for_status()
    activities = res.json()

    for activity in activities['activities']:
        # the 'Talks' activity defines our ticket capacity of the conference
        if 'Talks' in activity['name']:
            tickets['sold'] = activity['allocation_count']
            tickets['capacity'] = activity['capacity']
            tickets['left'] = tickets['capacity'] - tickets['sold']
            break

    return tickets


def get_cached_tickets_data():
    global _tickets_data_cache
    if not _tickets_data_cache:
        _tickets_data_cache = retrieve_tickets_data()
    return {**_tickets_data_cache, 'cached': True}


def get_fresh_tickets_data():
    global _tickets_data_cache
    _tickets_data_cache = retrieve_tickets_data()
    return {**_tickets_data_cache, 'cached': False}


def tickets_index(request):
    tickets = get_cached_tickets_data()
    return TemplateResponse(request, 'tickets/tickets.html', {'tickets': tickets})


def tickets_ajax_content(request):
    tickets = get_fresh_tickets_data()
    return TemplateResponse(request, 'tickets/ajax_content.html', {'tickets': tickets})

pyconcz/templates/proposals/__form-field.html
{% load widget_tweaks %}

{% with field_obj.field.widget.input_type as input_type %}
    <div class="form-group pc-field-name--{{ field_obj.html_name }}">
        {% if input_type == 'checkbox' %}
            <div class="form-check">
                {% render_field field_obj class='form-check-input' %}
                {{ field_obj.label_tag }}
                {% if field_obj.help_text %}
                    <small class="form-text">{{ field_obj.help_text|safe|linebreaksbr }}</small>
                {% endif %}
            </div>
        {% else %}
            {{ field_obj.label_tag }}

            {% if not input_type or input_type == 'file' and field_obj.help_text %}
                <small class="form-text">{{ field_obj.help_text|safe|linebreaksbr }}</small>
            {% endif %}

            {% if form.is_bound %}
                {% if field_obj.errors %}
                    {% render_field field_obj class='form-control is-invalid' %}
                    {% for error in field_obj.errors %}
                        <div class="invalid-feedback">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% else %}
                    {% render_field field_obj class='form-control is-valid' %}
                {% endif %}
            {% else %}
                {% render_field field_obj class='form-control' %}
            {% endif %}

            {% if input_type and input_type != 'file' and field_obj.help_text %}
                <small class="form-text">{{ field_obj.help_text|safe|linebreaksbr }}</small>
            {% endif %}

        {% endif %}
    </div>
{% endwith %}

pyconcz/templates/proposals/__form_field.html
{% load widget_tweaks %}

{% with field_obj.field.widget.input_type as input_type %}
    <div class="form-group pc-field-name--{{ field_obj.html_name }}">
        {% if input_type == 'checkbox' %}
            <div class="form-check">
                {% render_field field_obj class='form-check-input' %}
                {{ field_obj.label_tag }}
                {% if field_obj.help_text %}
                    <small class="form-text">{{ field_obj.help_text|safe|linebreaksbr }}</small>
                {% endif %}
            </div>
        {% else %}
            {{ field_obj.label_tag }}

            {% if not input_type or input_type == 'file' and field_obj.help_text %}
                <small class="form-text">{{ field_obj.help_text|safe|linebreaksbr }}</small>
            {% endif %}

            {% if form.is_bound %}
                {% if field_obj.errors %}
                    {% render_field field_obj class='form-control is-invalid' %}
                    {% for error in field_obj.errors %}
                        <div class="invalid-feedback">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% else %}
                    {% render_field field_obj class='form-control is-valid' %}
                {% endif %}
            {% else %}
                {% render_field field_obj class='form-control' %}
            {% endif %}

            {% if input_type and input_type != 'file' and field_obj.help_text %}
                <small class="form-text">{{ field_obj.help_text|safe|linebreaksbr }}</small>
            {% endif %}

        {% endif %}
    </div>
{% endwith %}

pyconcz/templates/proposals/proposal_after.html
{% extends '_layout.html' %}



{% block meta_title %}Call for Papers is closed – {{ block.super }}{% endblock %}


{% block main %}
    <div class="container">
        <h1>Call for Papers is closed!</h1>

        <p class="lead">{% block cfp_status %}{% endblock %}</p>
    </div>
{% endblock %}

pyconcz/templates/proposals/proposal_before.html
{% extends '_layout.html' %}



{% block meta_title %}Call for Papers opens soon – {{ block.super }}{% endblock %}


{% block main %}
    <div class="container">
        <h1>Call for Papers opens soon</h1>

        <p class="lead">Start submitting your proposals in <strong>{{ proposal_config.date_start|timeuntil }}</strong>!</p>
    </div>
{% endblock %}

pyconcz/templates/proposals/proposal_form.html
{% extends '_layout.html' %}


{% block meta_title %}{{ proposal_config.cfp_title|safe }} – {{ block.super }}{% endblock %}


{% block main %}
    <div class="container">

        <h1>{{ proposal_config.cfp_title|safe }}</h1>

        {% if proposal_config.key == 'financial-aid' %}
            <p class="lead">
                Financial aid applications <b>close on {{ proposal_config.date_end|date:'F j' }}</b>.
                Learn more about <a href="{% url 'proposal_about' key='financial-aid' %}">Financial Aid programme</a>.
            </p>
            <p>All answers will be used only to evaluate eligibility for Financial Aid and will be handled according to <a href="{% url 'privacy_policy' %}">PyCon CZ Privacy Policy</a>.</p>
        {% else %}
            <p class="lead">
                The Call for Proposals for {{ proposal_config.key }}
                will close on {{ proposal_config.date_end|date:'d F H:i e' }}
            </p>
        {% endif %}
    </div>

    <form action="" method="post" {% if form.is_multipart %}enctype="multipart/form-data"{% endif %}>
        {% csrf_token %}

        {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}

        {% if form.non_field_errors %}
            <div class="container">
                <div class="alert alert-danger" role="alert">
                    {% for error in form.non_field_errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
        {% endif %}

        {% if proposal_config.key != 'financial-aid' %}
            <div class="container">

                <h2>Public information</h2>
                <p>The following information will be displayed publicly if your proposal is selected. <strong>We check and proofread everything before publishing but please make our volunteer jobs easier and make sure we don’t have much to do.</strong></p>

                    {% include 'proposals/__form_field.html' with field_obj=form.language %}
                    {% if proposal_config.key == 'workshops' %}
                        {% include 'proposals/__form_field.html' with field_obj=form.type %}
                        {% include 'proposals/__form_field.html' with field_obj=form.length %}
                    {% endif %}
                    {% include 'proposals/__form_field.html' with field_obj=form.title %}
                    {% include 'proposals/__form_field.html' with field_obj=form.abstract %}
                    {% include 'proposals/__form_field.html' with field_obj=form.difficulty %}

                    <p class="font-italic small">If you are a&nbsp;speaker pair, write information about both of you in one field.</p>
                    {% include 'proposals/__form_field.html' with field_obj=form.full_name %}
                    {% include 'proposals/__form_field.html' with field_obj=form.bio %}
                    {% include 'proposals/__form_field.html' with field_obj=form.photo %}
                    {% include 'proposals/__form_field.html' with field_obj=form.twitter %}
                    {% include 'proposals/__form_field.html' with field_obj=form.github %}
                </div>
            </div>
        {% endif %}

        <div class="container">
            {% if proposal_config.key != 'financial-aid' %}
                <h2>Private information</h2>
                <p class="text-center">The following information will <b>not</b> be displayed publicly.</p>
            {% endif %}

            {% if proposal_config.key == 'financial-aid' %}
                {% include 'proposals/__form_field.html' with field_obj=form.full_name %}
            {% endif %}
            {% include 'proposals/__form_field.html' with field_obj=form.email %}
            {% include 'proposals/__form_field.html' with field_obj=form.amount %}
            {% include 'proposals/__form_field.html' with field_obj=form.purpose %}
            {% include 'proposals/__form_field.html' with field_obj=form.python_involvement %}
            {% if proposal_config.key == 'financial-aid' %}
                {% include 'proposals/__form_field.html' with field_obj=form.community_involvement %}
            {% endif %}
            {% include 'proposals/__form_field.html' with field_obj=form.referral_link %}
            {% include 'proposals/__form_field.html' with field_obj=form.needs_finaid %}
            {% include 'proposals/__form_field.html' with field_obj=form.finaid_details %}

            {% if proposal_config.key == 'workshops' %}
                {% include 'proposals/__form_field.html' with field_obj=form.requirements %}
            {% endif %}
            {% include 'proposals/__form_field.html' with field_obj=form.final_note %}
            {% include 'proposals/__form_field.html' with field_obj=form.gdpr_consent %}

            <p>Please note that you won’t receive any copy of your {% if proposal_config.key == 'financial-aid' %}application{% else %}proposal{% endif %} to your mailbox.</p>

            <button type="submit" class="btn btn-lg btn-primary mb-5">
                Submit your<br class="d-sm-none"> {% if proposal_config.key == 'financial-aid' %}application{% else %}proposal{% endif %}
            </button>
        </div>

        {% comment %}
        {# iterate over all fields #}
        {% for field in form.visible_fields %}
            {% include 'proposals/__form-field.html' with field_obj=field %}
        {% endfor %}
        {% endcomment %}
    </form>

    {% if proposal_config.key != 'financial-aid' %}
        <script>
            window.onload = function(){
                var extra = document.querySelector('.pc-field-name--finaid_details');
                var controlInput = document.querySelector('#id_needs_finaid');

                if (controlInput && extra){
                    function toggleInput(){
                        if (controlInput.checked){
                            extra.classList.remove('sr-only');
                        } else {
                            extra.classList.add('sr-only');
                        }
                    }

                    toggleInput();
                    controlInput.addEventListener('change', toggleInput, false);
                }
            }
        </script>
    {% endif %}

{% endblock %}

pyconcz/templates/proposals/proposal_success.html
{% extends '_layout.html' %}


{% block meta_title %}Sent {{ proposal_config.cfp_title|safe }} – {{ block.super }}{% endblock %}


{% block main %}
    <div class="container">
        {% if proposal_config_key == 'financial-aid' %}
            <h1>Application sent</h1>

            <p class="lead">You’ve submited your application successfully.</p>

            <p>Now please wait for an e-mail from <a href="mailto:info@pycon.cz">info@pycon.cz</a>.</p>

            <p>We’ll inform you about the result before the end of {{ proposal_config.date_end|date:'F' }} whether your application will be successfull or not.</p>

            <p>Please keep in mind, that our budget is limited and if there will be too many applications we won’t be able to help everyone.</p>

            <p>If you have any questions, don’t hesitate to <a href="mailto:info@pycon.cz">contact us</a>.</p>
        {% else %}
            <h1>Proposal sent</h1>

            <p class="h3">Thank you! <br>We’ve received your proposal.</p>

            <p>Please note that you won’t receive any copy or confirmation of your proposal to your mailbox.</p>

            <p>
                Scoring of submissions starts <strong>after</strong> Call for Papers ends and takes usually a&nbsp;week.
                <br>After it finishes, we email you results to the address you provided.
            </p>
            <p>If you have any questions, don’t hesitate to write us at <a href="mailto:info@pycon.cz">info@pycon.cz</a></p>

            <div class="row">
                    <div class="col">
                        <a class="btn btn-lg btn-primary btn-block" href="{% url 'proposal_form' key='talks' %}">
                            {% if proposal_config_key == 'talks' %}
                                Submit another talk
                            {% else %}
                                Submit your talk
                            {% endif %}
                        </a>
                    </div>
                    <div class="col">
                        <a class="btn btn-lg btn-primary btn-block" href="{% url 'proposal_form' key='workshops' %}">
                            {% if proposal_config_key == 'workshops' %}
                                Submit another workshop
                            {% else %}
                                Submit your workshop
                            {% endif %}
                        </a>
                    </div>
            </div>
        {% endif %}
    </div>
{% endblock %}